<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RealUserSeeder extends Seeder
{
    public function run()
    {
        $users = [
            [
                'name' => 'Tanti Yulianita',
                'nik' => '1872.MTK.0622',
                'email' => 'tanti.yulianita@ptmjl.co.id',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'ADMINISTRATOR',
                'roles' => 'admin',
                'nowa' => '0881022450222',
                'password' => '$2y$10$zHSkghpnQLYKIYY.eGe/yuDH0AriDiwm.2TLgVU/bfckFLtCKgQtq',
            ],
            [
                'name' => 'CHOIRUL ROZAQ',
                'nik' => 'admin',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'ADMINISTRATOR',
                'roles' => 'admin',
                'nowa' => '08122995054',
                'password' => '$2y$10$atuKvXDkVom00Whsyk8YZuP55Er1gvp63JTj6lRA2jOJ6sfv4/vVa',
            ],
            [
                'name' => 'HEE RENALD MAMANGKEY',
                'nik' => '0001.MTK.0209',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'DIREKTUR UTAMA',
                'roles' => 'pusat',
                'nowa' => '0811275033',
                'password' => '$2y$10$nvBVNP/G4fIBWxPMCGH89uz3zwzII9VFTUSyk.YaOO18phxLuqWsy',
            ],
            [
                'name' => 'NG BARNABAS',
                'nik' => '1152.MTK.0209',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'KOMISARIS',
                'roles' => 'pusat',
                'nowa' => '',
                'password' => '$2y$10$BwK6O2EH0FsZ28vYS33Xiur.HDwPesOV1MIui2/BNVZZmlMuugDRi',
            ],
            [
                'name' => 'ASRI RIANA DWIJAYANTI',
                'nik' => '0004.MTK.0209',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'SUPERVISOR',
                'roles' => 'admin',
                'nowa' => '',
                'password' => '$2y$10$BoAKMZJbAkkxXr/K9eN.6uzWe38A4AdtpeKuJL.dEor2lwGWBNlmu',
            ],
            [
                'name' => 'YULI FITRIYANI',
                'nik' => '0017.MTK.0609',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'SUPERVISOR',
                'roles' => 'pusat',
                'nowa' => '',
                'password' => '$2y$10$zHSkghpnQLYKIYY.eGe/yuDH0AriDiwm.2TLgVU/bfckFLtCKgQtq',
            ],
            [
                'name' => 'ABDULLAH JUNAIDI',
                'nik' => '0595.MTK.1115',
                'email' => 'junaidi.ksm@ptmjl.co.id',
                'region' => 'KSM',
                'unit' => 'HO KSM',
                'jabatan' => 'DIREKTUR PT',
                'roles' => 'region',
                'nowa' => '',
                'password' => '$2y$10$daN0IMGAV6pzH3zVplZkO.5Wkz7v5ek8xxZIvjzRzHZLh6esBnAWW',
            ],
            [
                'name' => 'SUSI SUSANTI',
                'nik' => '0261.MTK.0913',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'SUPERVISOR',
                'roles' => 'pusat',
                'nowa' => '',
                'password' => '$2y$10$zHSkghpnQLYKIYY.eGe/yuDH0AriDiwm.2TLgVU/bfckFLtCKgQtq',
            ],
            [
                'name' => 'DIMAS TONI SURYADI PUTRA',
                'nik' => '0856.MTK.0416',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'SUPERVISOR',
                'roles' => 'pusat',
                'nowa' => '',
                'password' => '$2y$10$zHSkghpnQLYKIYY.eGe/yuDH0AriDiwm.2TLgVU/bfckFLtCKgQtq',
            ],
            [
                'name' => 'MUH FATIHU ROJAI',
                'nik' => '0613.MTK.1115',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'SUPERVISOR',
                'roles' => 'pusat',
                'nowa' => '',
                'password' => '$2y$10$/Mn/Gkn8yRltaMK2DF6cDO3kXF5FHPAH38EaBKUpNAHHPFnwQG4RG',
            ],
            [
                'name' => 'ARIF SUMYANI',
                'nik' => '0120.MTK.0812',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'SUPERVISOR',
                'roles' => 'pusat',
                'nowa' => '082137149676',
                'password' => '$2y$10$2dwmbtr24ZvlPirKzB.6Z.4/3H066MgcZoK6QeNUIXVOvYhj/ool2',
            ],
            [
                'name' => 'TERI LINDAWATI',
                'nik' => '0034.MTK.0110',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'SUPERVISOR',
                'roles' => 'pusat',
                'nowa' => '',
                'password' => '$2y$10$y6DHKY6GBWsUYr6abT.AbuiYEOmp.Tj0uCm0yIAotbcu0Fnsddnbm',
            ],
            [
                'name' => 'DEWI SULISTIARINI',
                'nik' => '0022.MTK.1009',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'SUPERVISOR',
                'roles' => 'pusat',
                'nowa' => '085226196631',
                'password' => '$2y$10$zy9Z0vd92Ez7h69gBv2wTOaNY.rc1fG72K9TZjTzkPVJYeMjil6MC',
            ],
            [
                'name' => 'PRATIWI ADI SUTARTO',
                'nik' => '0110.MTK.0412',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'SUPERVISOR',
                'roles' => 'admin',
                'nowa' => '',
                'password' => '$2y$10$TVNzvClGNbr/gwLNkwTZruajZfiHvaVuPXHQz3IftxQrUt4Ps7Z8q',
            ],
            [
                'name' => 'DWIYANTO',
                'nik' => '0033.MTK.0110',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'SUPERVISOR',
                'roles' => 'pusat',
                'nowa' => '',
                'password' => '$2y$10$zuYrZphUID6OLKXmAwUd6uzv6xhcvXFeD4En9OC3IxtkrSFkvLvP2',
            ],
            [
                'name' => 'NIA DWI FITRIARINI',
                'nik' => '0065.MTK.1011',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'SUPERVISOR',
                'roles' => 'admin',
                'nowa' => '',
                'password' => '$2y$10$2bkskTIOdERosVI/3FHnbeHTtNDwPFrIAbpPYGeiwNpiA1fsN4u4G',
            ],
            [
                'name' => 'Y SOFE MEIYANTOKO',
                'nik' => '0008.MTK.0309',
                'email' => 'sofe@ptmjl.co.id',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'ADMINISTRATOR',
                'roles' => 'admin',
                'nowa' => '085228403413',
                'password' => '$2y$10$/xQAf.MZGk6wI0euOpiNCOGjp84.Pf7Ky6KKmkOXBZAlw0o5UTWzS',
            ],
            [
                'name' => 'WAHYU ARYADI',
                'nik' => '0036.MTK.0210',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'SUPERVISOR',
                'roles' => 'pusat',
                'nowa' => '081225847863',
                'password' => '$2y$10$R9na727j9S9H7knk63Whi..Ruk5w4P9E7a8rVwq/dN4vDMa4Zztq6',
            ],
            [
                'name' => 'SATRIYO PRAYOGO WICAKSONO',
                'nik' => '0315.MTK.1213',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'SUPERVISOR',
                'roles' => 'pusat',
                'nowa' => '085803779698',
                'password' => '$2y$10$KK7Joy9/3UHT8ZKDObV8hu9S8FpVtOIaDY79rcarAyk4x3nEvfO3.',
            ],
            [
                'name' => 'PARADITA PRAMESTHIAN',
                'nik' => '0069.MTK.1011',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'STAFF FINANCE',
                'roles' => 'pusat',
                'nowa' => '',
                'password' => '$2y$10$aLRHTxlMFrN6WYzu2WqTrucc.XzFIfycSew1NNDSPE4ZdkFMKi0nK',
            ],
            [
                'name' => 'CHOIRUL ROZAQ',
                'nik' => '1287.MTK.0717',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'ADMINISTRATOR',
                'roles' => 'admin',
                'nowa' => '08122995054',
                'password' => '$2y$10$TCOZgM9SDUCCLDiOkS1g2e2mBhZVFrQ85M8Si1Dn4Odf8vUS5099a',
            ],
            [
                'name' => 'SOFI MUDRIKAH',
                'nik' => '0447.MTK.0515',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'STAFF PENJUALAN',
                'roles' => 'admin',
                'nowa' => '',
                'password' => '$2y$10$edWs8WdCUrfJF4Ka1Sbap.bTYbmI1k7tw4t.W/VegImoJrasINDTa',
            ],
            [
                'name' => 'TRI UTAMI HANDAYANI',
                'nik' => '0267.MTK.1013',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'STAFF HRD',
                'roles' => 'pusat',
                'nowa' => '',
                'password' => '$2y$10$zHSkghpnQLYKIYY.eGe/yuDH0AriDiwm.2TLgVU/bfckFLtCKgQtq',
            ],
            [
                'name' => 'TRI SUHARYATI',
                'nik' => '0639.MTK.1215',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'STAFF HRD',
                'roles' => 'pusat',
                'nowa' => '082232810884',
                'password' => '$2y$10$zHSkghpnQLYKIYY.eGe/yuDH0AriDiwm.2TLgVU/bfckFLtCKgQtq',
            ],
            [
                'name' => 'HERU HARIYANTO',
                'nik' => '0340.MTK.0714',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'STAFF DEVELOPMENT',
                'roles' => 'pusat',
                'nowa' => '082137565389',
                'password' => '$2y$10$2tBQ.DaFtMLoW2Q2humLyueeUyDUbg9qzb1Du89tQD57baBMT7lHi',
            ],
            [
                'name' => 'MAHAPUTRA TRAH BINATHORO',
                'nik' => '0945.MTK.1115',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'ADMINISTRATOR',
                'roles' => 'admin',
                'nowa' => '',
                'password' => '$2y$10$E7edQprMxQcl7QTegarDHeiMpj4NfziBWIH/ypM0nNzqA0y9XapRO',
            ],
            [
                'name' => 'DEWI SAFITRI',
                'nik' => '0161.MTK.0113',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'STAFF IA',
                'roles' => 'pusat',
                'nowa' => '087735498961',
                'password' => '$2y$10$zHSkghpnQLYKIYY.eGe/yuDH0AriDiwm.2TLgVU/bfckFLtCKgQtq',
            ],
            [
                'name' => 'INAYAH LISTIANINGSIH',
                'nik' => '0295.MTK.1113',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'STAFF HRD',
                'roles' => 'pusat',
                'nowa' => '',
                'password' => '$2y$10$/JW67B0i.32T3BEZSESyjeRXiMiJfzPIPuZrQuHyGldXVhJ38MEDm',
            ],
            [
                'name' => 'LINDA SAFITRI',
                'nik' => '1505.MTK.1018',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'STAFF IA',
                'roles' => 'pusat',
                'nowa' => '087778848332',
                'password' => '$2y$10$zHSkghpnQLYKIYY.eGe/yuDH0AriDiwm.2TLgVU/bfckFLtCKgQtq',
            ],
            [
                'name' => 'VANIA DEYA JENA AQKDA',
                'nik' => '1540.MTK.0119',
                'email' => '',
                'region' => 'KLB',
                'unit' => 'HO KLB',
                'jabatan' => 'STAFF REGION',
                'roles' => 'sr',
                'nowa' => '087888756591',
                'password' => '$2y$10$yN54Bc9n3frlMoeO506A4eYQGkIFmBTq44ZFlIelIUpIEjM8g8zDu',
            ],
            [
                'name' => 'DENIS PURWANTI',
                'nik' => '1541.MTK.0119',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'STAFF IA',
                'roles' => 'pusat',
                'nowa' => '085867558935',
                'password' => '$2y$10$VXoEGVr4F25YR29iAw5hg.ivJnRmb7uMUQ3LXHLAOJXv3Ql32Ja2q',
            ],
            [
                'name' => 'RACHMAD SUBEKTI',
                'nik' => '0053.MTK.0811',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'STAFF PAJAK',
                'roles' => 'pusat',
                'nowa' => '085741143371',
                'password' => '$2y$10$zHSkghpnQLYKIYY.eGe/yuDH0AriDiwm.2TLgVU/bfckFLtCKgQtq',
            ],
            [
                'name' => 'ELIS SETYAWATI',
                'nik' => '0126.MTK.0912',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'STAFF PAJAK',
                'roles' => 'pusat',
                'nowa' => '',
                'password' => '$2y$10$CU1aA62nmNaPzGCsZ9dTO.wy5nIzJxbl.ADFqN1E5JUBwwukV7LfC',
            ],
            [
                'name' => 'ASRI MARIANY',
                'nik' => '1498.MTK.0918',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'STAFF PAJAK',
                'roles' => 'pusat',
                'nowa' => '085742228355',
                'password' => '$2y$10$zHSkghpnQLYKIYY.eGe/yuDH0AriDiwm.2TLgVU/bfckFLtCKgQtq',
            ],
            [
                'name' => 'INDONAH',
                'nik' => '0191.MTK.0313',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'STAFF FINANCE',
                'roles' => 'pusat',
                'nowa' => '',
                'password' => '$2y$10$zHSkghpnQLYKIYY.eGe/yuDH0AriDiwm.2TLgVU/bfckFLtCKgQtq',
            ],
            [
                'name' => 'ANISA YULIANA',
                'nik' => '0256.MTK.0913',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'STAFF FINANCE',
                'roles' => 'pusat',
                'nowa' => '',
                'password' => '$2y$10$zHSkghpnQLYKIYY.eGe/yuDH0AriDiwm.2TLgVU/bfckFLtCKgQtq',
            ],
            [
                'name' => 'ROSSI KUSUMA JATI',
                'nik' => '0614.MTK.1115',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'STAFF FINANCE',
                'roles' => 'pusat',
                'nowa' => '',
                'password' => '$2y$10$zHSkghpnQLYKIYY.eGe/yuDH0AriDiwm.2TLgVU/bfckFLtCKgQtq',
            ],
            [
                'name' => 'ALI MUHSON',
                'nik' => '1551.MTK.0219',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'STAFF LEGAL',
                'roles' => 'pusat',
                'nowa' => '085602287174',
                'password' => '$2y$10$gjsV2Zzxhu848ppY6IicbeVX5ZwZ8T6ljPbVU81mTts.bUgDCImXO',
            ],
            [
                'name' => 'VELIEKA APRILIANI',
                'nik' => '0309.MTK.1113',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'AKUNTING',
                'roles' => 'pusat',
                'nowa' => '085800001288',
                'password' => '$2y$10$2tNHkZ2Nol8yqKiB5y3sEOPsr8DV3tO02LG/snS2v2u/bsuD/v57m',
            ],
            [
                'name' => 'NANDA BAGUS FAVIANTO',
                'nik' => '0392.MTK.1114',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'AKUNTING',
                'roles' => 'pusat',
                'nowa' => '085867302506',
                'password' => '$2y$10$SKp31UdNijqnaSm5LID8GuKx4/DSfFVz2bB2eBBl0B.Uq9ZCbV6xq',
            ],
            [
                'name' => 'JULYANTI PURNAMASARI',
                'nik' => '1073.MTK.0916',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'AKUNTING',
                'roles' => 'pusat',
                'nowa' => '',
                'password' => '$2y$10$zHSkghpnQLYKIYY.eGe/yuDH0AriDiwm.2TLgVU/bfckFLtCKgQtq',
            ],
            [
                'name' => 'SITI KURNIA APRILIYANI',
                'nik' => '1556.MTK.0219',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'AKUNTING',
                'roles' => 'pusat',
                'nowa' => '081326622242',
                'password' => '$2y$10$zHSkghpnQLYKIYY.eGe/yuDH0AriDiwm.2TLgVU/bfckFLtCKgQtq',
            ],
            [
                'name' => 'DWI BOWO',
                'nik' => '1732.MTK.0520',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'STAFF LEGAL',
                'roles' => 'pusat',
                'nowa' => '',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
            ],
            [
                'name' => 'DWI ARIANTO',
                'nik' => '0538.MTK.0915',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'STAFF LEGAL',
                'roles' => 'pusat',
                'nowa' => '',
                'password' => '$2y$10$zHSkghpnQLYKIYY.eGe/yuDH0AriDiwm.2TLgVU/bfckFLtCKgQtq',
            ],
            [
                'name' => 'FADLU MUHAMMAD AMRULLOH',
                'nik' => '1761.MTK.0121',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'ADMINISTRATOR',
                'roles' => 'admin',
                'nowa' => '089637806658',
                'password' => '$2y$10$5VslK3xKtEv0V8ZUUvZq.Or.m1KYPbYudrZtC0/QZAgeaEQV4nc8S',
            ],
            [
                'name' => 'SUSETYO AHMAD NUR ANNAFI',
                'nik' => '1845.MTK.0222',
                'email' => '',
                'region' => 'MJL',
                'unit' => 'HO',
                'jabatan' => 'AKUNTING',
                'roles' => 'pusat',
                'nowa' => '',
                'password' => '$2y$10$zHSkghpnQLYKIYY.eGe/yuDH0AriDiwm.2TLgVU/bfckFLtCKgQtq',
            ],
            [
                'name' => 'EVI NILAWATI',
                'nik' => '0020.MTK.1009',
                'email' => '',
                'region' => 'MUM',
                'unit' => 'HO MUM',
                'jabatan' => 'STAFF REGION',
                'roles' => 'sr',
                'nowa' => '082313394422',
                'password' => '$2y$10$lFDg9H.zGDJAzTJHL./i1OfcPwi9s4/H9kBHoSp.mzFTtyTMwNfYO',
            ],
            [
                'name' => 'BENI SISWANTO',
                'nik' => '0046.MTK.0311',
                'email' => '',
                'region' => 'MUM',
                'unit' => 'HO MUM',
                'jabatan' => 'DIREKTUR PT',
                'roles' => 'region',
                'nowa' => '',
                'password' => '$2y$10$CjVr//PCDDJuftjyXHP9dOXsOU2uR80KaxrX5/6niTpmCSOu4.bkq',
            ],
            [
                'name' => 'LELLY NOVIARTI',
                'nik' => '0260.MTK.0913',
                'email' => '',
                'region' => 'MUM',
                'unit' => 'HO MUM',
                'jabatan' => 'STAFF REGION',
                'roles' => 'sr',
                'nowa' => '085344755554',
                'password' => '$2y$10$zHSkghpnQLYKIYY.eGe/yuDH0AriDiwm.2TLgVU/bfckFLtCKgQtq',
            ],
            [
                'name' => 'YOHANES PUTRO NUGRAHA',
                'nik' => '1393.MTK.0218',
                'email' => '',
                'region' => 'MUM',
                'unit' => 'KLP',
                'jabatan' => 'SALES',
                'roles' => 'user',
                'nowa' => '',
                'password' => '$2y$10$dcRsRoB0l3Uiu1.TvCpu8uM54v.DugYZwVwudsoDI8GR8Ok8mbZmG',
            ],
        ];

        foreach ($users as $u) {
            \App\Models\User::updateOrCreate(['nik' => $u['nik']], $u);
        }
    }
}
