<?php

namespace Database\Seeders;

use App\Models\TaxStp;
use Illuminate\Database\Seeder;

class TaxStpSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        TaxStp::truncate();

        $dataset = [
            // 2026 STP Entries
            [
                'ap' => 'PT MUSTIKA JAYA LESTARI',
                'jenis_pajak' => 'PPh 21',
                'bulan' => '03',
                'tahun' => 2026,
                'nomor_stp' => '00012/101/26/501/000',
                'tanggal_bayar' => '2026-05-15',
                'tanggal_stp' => '2026-05-02',
                'nominal' => 1450000,
                'uraian' => 'STP Bunga Pasal 19 Ayat (1) KUP atas Keterlambatan Pembayaran PPh 21 Masa Maret 2026.',
                'bukti_bayar' => null,
            ],
            [
                'ap' => 'PT MUSTIKA JAYA LESTARI',
                'jenis_pajak' => 'PPN',
                'bulan' => '04',
                'tahun' => 2026,
                'nomor_stp' => '00045/107/26/501/000',
                'tanggal_bayar' => '2026-06-20',
                'tanggal_stp' => '2026-06-10',
                'nominal' => 3200000,
                'uraian' => 'STP Denda Pasal 7 KUP Keterlambatan Pelaporan SPT Masa PPN Masa April 2026 & Bunga Keterlambatan.',
                'bukti_bayar' => null,
            ],
            [
                'ap' => 'PT ANEKA INTAN LESTARI',
                'jenis_pajak' => 'PPh 23',
                'bulan' => '02',
                'tahun' => 2026,
                'nomor_stp' => '00088/103/26/512/000',
                'tanggal_bayar' => '2026-04-12',
                'tanggal_stp' => '2026-04-05',
                'nominal' => 650000,
                'uraian' => 'STP Sanksi Administrasi Bunga atas Kurang Setor PPh 23 Jasa Sewa Alat Angkut.',
                'bukti_bayar' => null,
            ],
            [
                'ap' => 'PT ANEKA INTAN LESTARI',
                'jenis_pajak' => 'PPh 21',
                'bulan' => '05',
                'tahun' => 2026,
                'nomor_stp' => '00112/101/26/512/000',
                'tanggal_bayar' => '2026-07-08',
                'tanggal_stp' => '2026-06-28',
                'nominal' => 1150000,
                'uraian' => 'STP Bunga Keterlambatan Setor PPh 21 Masa Mei 2026.',
                'bukti_bayar' => null,
            ],
            [
                'ap' => 'PT MITRA UNGGAS MAKMUR',
                'jenis_pajak' => 'PPN',
                'bulan' => '03',
                'tahun' => 2026,
                'nomor_stp' => '00072/107/26/501/000',
                'tanggal_bayar' => '2026-05-22',
                'tanggal_stp' => '2026-05-14',
                'nominal' => 2800000,
                'uraian' => 'STP Denda Keterlambatan Terbit Faktur Pajak Keluaran Penjualan Livebird.',
                'bukti_bayar' => null,
            ],
            [
                'ap' => 'PT MITRA UNGGAS MAKMUR',
                'jenis_pajak' => 'PPh Pasal 4 Ayat 2',
                'bulan' => '04',
                'tahun' => 2026,
                'nomor_stp' => '00095/104/26/501/000',
                'tanggal_bayar' => '2026-06-18',
                'tanggal_stp' => '2026-06-05',
                'nominal' => 900000,
                'uraian' => 'STP Sanksi Bunga Pasal 19 Ayat (1) atas Sewa Lahan Kandang Farm Ungaran.',
                'bukti_bayar' => null,
            ],
            [
                'ap' => 'PT LAWU ABADI NUSA',
                'jenis_pajak' => 'PPh 25',
                'bulan' => '05',
                'tahun' => 2026,
                'nomor_stp' => '00104/105/26/528/000',
                'tanggal_bayar' => '2026-07-15',
                'tanggal_stp' => '2026-07-02',
                'nominal' => 1750000,
                'uraian' => 'STP Bunga Keterlambatan Angsuran Bulanan PPh 25 Badan Masa Mei 2026.',
                'bukti_bayar' => null,
            ],
            [
                'ap' => 'PT MURIA JAYA RAYA',
                'jenis_pajak' => 'PPN',
                'bulan' => '06',
                'tahun' => 2026,
                'nomor_stp' => '00130/107/26/506/000',
                'tanggal_bayar' => '2026-08-14',
                'tanggal_stp' => '2026-08-01',
                'nominal' => 2400000,
                'uraian' => 'STP Bunga Pajak atas Koreksi Faktur Pengganti PPN Pakan Ternak Masa Juni.',
                'bukti_bayar' => null,
            ],
            [
                'ap' => 'PT KEDU LINTAS BERBINTANG',
                'jenis_pajak' => 'PPh 21',
                'bulan' => '04',
                'tahun' => 2026,
                'nomor_stp' => '00084/101/26/524/000',
                'tanggal_bayar' => '2026-06-10',
                'tanggal_stp' => '2026-05-28',
                'nominal' => 1250000,
                'uraian' => 'STP Keterlambatan Setor PPh 21 Masa April 2026 Unit Magelang.',
                'bukti_bayar' => null,
            ],
            [
                'ap' => 'PT BAROKAH RESTU UTAMA',
                'jenis_pajak' => 'PPh 22',
                'bulan' => '03',
                'tahun' => 2026,
                'nomor_stp' => '00067/102/26/517/000',
                'tanggal_bayar' => '2026-05-18',
                'tanggal_stp' => '2026-05-06',
                'nominal' => 850000,
                'uraian' => 'STP Bunga Pembelian Jagung Pakan Tanpa NPWP Rekanan Petani.',
                'bukti_bayar' => null,
            ],
            [
                'ap' => 'PT BINTANG TERANG BERSINAR',
                'jenis_pajak' => 'PPN',
                'bulan' => '05',
                'tahun' => 2026,
                'nomor_stp' => '00115/107/26/531/000',
                'tanggal_bayar' => '2026-07-20',
                'tanggal_stp' => '2026-07-09',
                'nominal' => 1950000,
                'uraian' => 'STP Denda Keterlambatan Lapor PPN Masa Mei 2026 Wilayah Banyumas.',
                'bukti_bayar' => null,
            ],
            [
                'ap' => 'PT GILAR PERWIRA SATRIA',
                'jenis_pajak' => 'PPh 21',
                'bulan' => '06',
                'tahun' => 2026,
                'nomor_stp' => '00142/101/26/532/000',
                'tanggal_bayar' => '2026-08-15',
                'tanggal_stp' => '2026-08-03',
                'nominal' => 950000,
                'uraian' => 'STP Bunga Keterlambatan PPh 21 Tenaga Panen Banjarnegara.',
                'bukti_bayar' => null,
            ],
            [
                'ap' => 'PT KARYA SATWA MULIA',
                'jenis_pajak' => 'PPh 23',
                'bulan' => '04',
                'tahun' => 2026,
                'nomor_stp' => '00099/103/26/508/000',
                'tanggal_bayar' => '2026-06-25',
                'tanggal_stp' => '2026-06-11',
                'nominal' => 550000,
                'uraian' => 'STP Bunga Jasa Pemeliharaan Mesin Kandang Close-House Salatiga.',
                'bukti_bayar' => null,
            ],
            [
                'ap' => 'PT LAJU SATWA WISESA',
                'jenis_pajak' => 'PPh 21',
                'bulan' => '05',
                'tahun' => 2026,
                'nomor_stp' => '00118/101/26/503/000',
                'tanggal_bayar' => '2026-07-14',
                'tanggal_stp' => '2026-07-01',
                'nominal' => 1350000,
                'uraian' => 'STP Sanksi Bunga Pasal 19 Ayat (1) Gaji Staf Logistik Semarang.',
                'bukti_bayar' => null,
            ],
            [
                'ap' => 'PT MITRA MAHKOTA BUANA',
                'jenis_pajak' => 'PPN',
                'bulan' => '06',
                'tahun' => 2026,
                'nomor_stp' => '00138/107/26/511/000',
                'tanggal_bayar' => '2026-08-20',
                'tanggal_stp' => '2026-08-08',
                'nominal' => 2100000,
                'uraian' => 'STP Bunga Kurang Bayar PPN Pengiriman DOC Tegal & Brebes.',
                'bukti_bayar' => null,
            ],
            [
                'ap' => 'PT MITRA PETERNAKAN UNGGAS',
                'jenis_pajak' => 'PPh 25',
                'bulan' => '06',
                'tahun' => 2026,
                'nomor_stp' => '00140/105/26/521/000',
                'tanggal_bayar' => '2026-08-16',
                'tanggal_stp' => '2026-08-05',
                'nominal' => 1650000,
                'uraian' => 'STP Sanksi Bunga Angsuran PPh 25 Badan Pekalongan Masa Juni 2026.',
                'bukti_bayar' => null,
            ],
            [
                'ap' => 'PT SAWUNG GEMA ABADI',
                'jenis_pajak' => 'PPh Pasal 4 Ayat 2',
                'bulan' => '03',
                'tahun' => 2026,
                'nomor_stp' => '00078/104/26/515/000',
                'tanggal_bayar' => '2026-05-12',
                'tanggal_stp' => '2026-04-29',
                'nominal' => 1800000,
                'uraian' => 'STP Bunga Keterlambatan Sewa Gedung Cold Storage Sukoharjo.',
                'bukti_bayar' => null,
            ],

            // 2025 STP Entries
            [
                'ap' => 'PT MUSTIKA JAYA LESTARI',
                'jenis_pajak' => 'PPh 21',
                'bulan' => '11',
                'tahun' => 2025,
                'nomor_stp' => '00210/101/25/501/000',
                'tanggal_bayar' => '2026-01-15',
                'tanggal_stp' => '2026-01-05',
                'nominal' => 1850000,
                'uraian' => 'STP Bunga Keterlambatan Setor PPh 21 Masa November 2025 HO.',
                'bukti_bayar' => null,
            ],
            [
                'ap' => 'PT MUSTIKA JAYA LESTARI',
                'jenis_pajak' => 'PPN',
                'bulan' => '10',
                'tahun' => 2025,
                'nomor_stp' => '00195/107/25/501/000',
                'tanggal_bayar' => '2025-12-18',
                'tanggal_stp' => '2025-12-04',
                'nominal' => 3800000,
                'uraian' => 'STP Sanksi Bunga Faktur Pengganti PPN Sarana Produksi Ternak.',
                'bukti_bayar' => null,
            ],
            [
                'ap' => 'PT ANEKA INTAN LESTARI',
                'jenis_pajak' => 'PPN',
                'bulan' => '08',
                'tahun' => 2025,
                'nomor_stp' => '00160/107/25/512/000',
                'tanggal_bayar' => '2025-10-12',
                'tanggal_stp' => '2025-09-29',
                'nominal' => 2200000,
                'uraian' => 'STP Denda Terlambat Lapor PPN Masa Agustus 2025 Klaten.',
                'bukti_bayar' => null,
            ],
            [
                'ap' => 'PT MITRA UNGGAS MAKMUR',
                'jenis_pajak' => 'PPh 23',
                'bulan' => '09',
                'tahun' => 2025,
                'nomor_stp' => '00175/103/25/501/000',
                'tanggal_bayar' => '2025-11-15',
                'tanggal_stp' => '2025-11-02',
                'nominal' => 750000,
                'uraian' => 'STP Bunga Jasa Kalibrasi Timbangan dan Ekspedisi Pakan.',
                'bukti_bayar' => null,
            ],
            [
                'ap' => 'PT LAWU ABADI NUSA',
                'jenis_pajak' => 'PPh 21',
                'bulan' => '09',
                'tahun' => 2025,
                'nomor_stp' => '00178/101/25/528/000',
                'tanggal_bayar' => '2025-11-10',
                'tanggal_stp' => '2025-10-28',
                'nominal' => 1100000,
                'uraian' => 'STP Bunga Keterlambatan Gaji Farm Sragen Masa September 2025.',
                'bukti_bayar' => null,
            ],
            [
                'ap' => 'PT MURIA JAYA RAYA',
                'jenis_pajak' => 'PPh 25',
                'bulan' => '08',
                'tahun' => 2025,
                'nomor_stp' => '00162/105/25/506/000',
                'tanggal_bayar' => '2025-10-14',
                'tanggal_stp' => '2025-10-01',
                'nominal' => 1400000,
                'uraian' => 'STP Bunga Angsuran Bulanan PPh 25 Badan Kudus Masa Agustus 2025.',
                'bukti_bayar' => null,
            ],
            [
                'ap' => 'PT KEDU LINTAS BERBINTANG',
                'jenis_pajak' => 'PPN',
                'bulan' => '07',
                'tahun' => 2025,
                'nomor_stp' => '00148/107/25/524/000',
                'tanggal_bayar' => '2025-09-18',
                'tanggal_stp' => '2025-09-05',
                'nominal' => 1900000,
                'uraian' => 'STP Denda Administrasi Faktur Pajak Batal Masa Juli 2025.',
                'bukti_bayar' => null,
            ],
        ];

        foreach ($dataset as $row) {
            TaxStp::create($row);
        }
    }
}
